test(internal/sidekick): skip test instead of failing when cargo is not installed (#2102)
`go test ./...` should always pass on a fresh clone of
github.com/librarian/googleapis.

At the moment, TestRustProstFromProtobuf fails because it requires
cargo.

```
--- FAIL: TestRustProstFromProtobuf (0.09s)
    sidekick_rust_prost_test.go:48: got an error trying to run `cargo
    --version`, the instructions on
    https://www.rust-lang.org/learn/get-started may solve this problem:
    cargo --version: exec: "cargo": executable file not found in $PATH
```

Skip this test when cargo is not installed.